services:
  backend:
    image: ${DOCKERHUB_USERNAME}/minishop-backend:${IMAGE_TAG:-latest}
    container_name: minishop-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      # Biến này sẽ lấy từ GitHub Secrets mà Mạnh đã cài đặt
      MONGODB_URI: ${MONGODB_URI}
      CORS_ORIGIN: ${CORS_ORIGIN}
    # Đã xóa mongo khỏi depends_on vì dùng MongoDB cài trực tiếp trên Host
    expose:
      - "3000"

  frontend:
    image: ${DOCKERHUB_USERNAME}/minishop-frontend:${IMAGE_TAG:-latest}
    container_name: minishop-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8081:80" # Đổi thành 8081 để không bị lỗi "Address already in use" với Nginx cổng 80