services:
  backend:
    image: ${DOCKERHUB_USERNAME}/minishop-backend:${IMAGE_TAG:-latest}
    container_name: minishop-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      # Biến này sẽ lấy từ GitHub Secrets mà Mạnh đã cài đặt
      MONGODB_URI: ${MONGODB_URI}
      CORS_ORIGIN: ${CORS_ORIGIN}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_SECURE: ${COOKIE_SECURE}
      COOKIE_SAME_SITE: ${COOKIE_SAME_SITE}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      MAIL_FROM: ${MAIL_FROM}
      VNP_TMN_CODE: ${VNP_TMN_CODE}
      VNP_HASH_SECRET: ${VNP_HASH_SECRET}
      VNP_URL: ${VNP_URL}
      VNP_RETURN_URL: ${VNP_RETURN_URL}
    # Đã xóa mongo khỏi depends_on vì dùng MongoDB cài trực tiếp trên Host
    expose:
      - "3000"
    volumes:
      - backend_uploads:/app/uploads

  frontend:
    image: ${DOCKERHUB_USERNAME}/minishop-frontend:${IMAGE_TAG:-latest}
    container_name: minishop-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8081:80" # Đổi thành 8081 để không bị lỗi "Address already in use" với Nginx cổng 80

volumes:
  backend_uploads: